<?php

class ToManyPropertiesTestClass
{
    /**
     * @var array
     */
    protected $array1;

    /**
     * @var bool
     */
    protected $boolean1;

    /**
     * @var boolean
     */
    protected $boolean2;

    /**
     * @var callable
     */
    protected $callable1;

    /**
     * @var double
     */
    protected $double1;

    /**
     * @var float
     */
    protected $float1;

    /**
     * @var int
     */
    protected $integer1;

    /**
     * @var integer
     */
    protected $integer2;

    /**
     * @var resource
     */
    protected $resource1;

    /**
     * @var string
     */
    protected $string1;

    /**
     * @var string
     */
    protected $string3;
    protected $string4;
    protected $string5;
    protected $string6;
    protected $string7;
    protected $string8;
    protected $string9;
    protected $string10;
    protected $string11;
    protected $string12;
    protected $string13;
    protected $string14;
    protected $string15;
    protected $string16;
    protected $string17;
    protected $string18;
}
